### ISSUE TITLE
API Enhancements

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#101]
Some useful functionality in Container JFR is not exposed via the operator's API. Some of this is existing in Container JFR today and some still a work-in-progress. Let's track what sorts of changes should go into the next version of our CRDs.

Confirmed:
- [x] Listing event templates in FlightRecorder (https://github.com/rh-jmc-team/container-jfr-operator/issues/100)
- [x] Report URL in Recordings (https://github.com/rh-jmc-team/container-jfr-operator/issues/89)
- [x] JMX authentication credentials in FlightRecorder/Recording (https://github.com/rh-jmc-team/container-jfr-operator/issues/98)
- [x] Add TrustedCertSecrets property to ContainerJFR CRD (#142)
- [x] Add application URL to Container JFR CRD (#187)
- [x] Options to control creation of Ingress objects on Kubernetes (#120)
- [x] Document new API additions (#134)

Declined:
- ~container-jfr log level env var should be controllable via CR spec (#63)~

Some other ideas:
- Use Conditions to inform the user about errors in spec that require fixing. (e.g. authentication failures)
- Enable/Disable security features ~~TLS hostname verification parameter in ContainerJFR spec~~
- Allow user to archive running recordings and archive a recording more than once

**Comment by ebaron** [comment]
With the documentation done, this is complete.
