### ISSUE TITLE
Port CI improvements from Cryostat

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#214]
The Cryostat repo has several additions to CI that we should also include in the operator.

- [x] #223
- [x] Enforcing Conventional Commits standard (#216)
- [x] Issue dependencies (#218)
- [x] Release Drafter for release notes (#217)
- [x] Mergify config for backport automation (#215)
