### ISSUE TITLE
[Epic] Multi-namespace support for Cryostat

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#501]
In order to support a Cryostat installation that works across namespaces (https://github.com/cryostatio/cryostat/issues/760), we'll need to make several changes to the operator. We should attempt these changes in a non-breaking way if possible. The general new architecture will be one instance of the operator for the cluster, which manages potentially multiple Cryostat installations, each with their own set of configured namespaces they may access.

Tasks:
- [x] https://github.com/cryostatio/cryostat-operator/issues/506
- [x] https://github.com/cryostatio/cryostat-operator/issues/502
- [x] https://github.com/cryostatio/cryostat-operator/issues/513
- [x] https://github.com/cryostatio/cryostat-operator/issues/542
- [x] https://github.com/cryostatio/cryostat-operator/issues/524
- [x] https://github.com/cryostatio/cryostat-operator/issues/521
- [x] https://github.com/cryostatio/cryostat-operator/issues/522
- [x] https://github.com/cryostatio/cryostat/issues/760
